openapi: "3.0.2"
info:
  title: Todo List API
  description: |
    Defines the endpoints and operations that manage todo lists and their related tasks and notes.

    See [Github repository](https://github.com/raro28/todo-api).
  version: "0.0.0"
  contact:
    name: Hector Diaz
    url: https://github.com/raro28
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://0.0.0.0:3001/v0
    description: mockoon server
  - url: http://localhost:8080
    description: spring-boot server

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    page:
      in: query
      name: page
      description: the 1 based page index
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 1
        maximum: 20000
    pageSize:
      in: query
      name: size
      description: the greater than zero page size
      schema:
        type: integer
        format: int32
        default: 5
        minimum: 1
        maximum: 50
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 1000000
      example: 0
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema: 
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 401
            error: Bad Request
            message: ""
            path: /foo/bar
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema: 
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 401
            error: Unauthorized
            message: ""
            path: /foo/bar
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema: 
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 403
            error: Forbidden
            message: ""
            path: /foo/bar
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 404
            error: Not found
            message: ""
            path: /foo/bar
    TooManyRequests:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 429
            error: Too Many Requests
            message: ""
            path: /foo/bar
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 500
            error: Internal Server Error
            message: ""
            path: /foo/bar
    UnknownError:
      description: Unknown Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            timestamp: 2020-06-07T10:30:10.694+00:00
            status: 500
            error: Unknown Error
            message: ""
            path: /foo/bar
  schemas:
    Error:
      type: object
      additionalProperties: false
      properties:
        timestamp:
          type: string
          pattern: \d{4}\-\d{2}\-\d{2}\w\d{2}:\d{2}:\d{2}\.\d{3}\+\d{2}:\d{2}
          maxLength: 30
        status:
          type: integer
          format: int32
          minimum: 0
          maximum: 1000000
        error:
          type: string
          pattern: ^[a-zA-Z0-9_\/]*$
          maxLength: 255
        message:
          type: string
          pattern: ^[a-zA-Z0-9_\/]*$
          maxLength: 255
        path:
          type: string
          pattern: ^[a-zA-Z0-9_\/]*$
          maxLength: 255
    DataResult:
      type: object
      additionalProperties: false
      properties:
        total:
          type: integer
          format: $int64
          minimum: 0
          maximum: 1000000
          description: The total sum of entries in all pages
        totalPages:
          type: integer
          format: $int32
          minimum: 0
          maximum: 20000
          description: The total sum of entries in all pages
    TaskListResult:
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/DataResult"
        - type: object
          properties:
                data:
                  type: array
                  maxItems: 50
                  items:
                    $ref: "#/components/schemas/TaskListEntity"
    TaskResult:
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/DataResult"
        - type: object
          properties:
                data:
                  type: array
                  maxItems: 50
                  items:
                    $ref: "#/components/schemas/TaskEntity"
    NoteResult:
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/DataResult"
        - type: object
          properties:
                data:
                  type: array
                  maxItems: 50
                  items:
                    $ref: "#/components/schemas/NoteEntity"
    Entity:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
          maximum: 1000000
    TaskList:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
          pattern: ^[a-zA-Z0-9]*$
          maxLength: 255
    Task:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
          pattern: ^[a-zA-Z0-9]*$
          maxLength: 255
        completed:
          type: boolean
    Note:
      type: object
      additionalProperties: false
      properties:
        content:
          type: string
          pattern: /^(?:[^%]|%[0-9A-Fa-f]{2})+$/
          maxLength: 500
    TaskListEntity:
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Entity"
        - $ref: "#/components/schemas/TaskList"
    TaskEntity:
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Entity"
        - $ref: "#/components/schemas/Task"
    NoteEntity:
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Entity"
        - $ref: "#/components/schemas/Note"

tags:
  - name: lists
  - name: tasks
  - name: notes
  - name: crud

security:
  - basicAuth: []

paths:
  /lists/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      tags:
        - lists
        - crud
      operationId: listsIdGet
      summary: Gets a task list by its id
      responses:
        "200":
          description: A task list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskList"
              example:
                title: Clean house
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    delete:
      tags:
        - lists
        - crud
      operationId: listsIdDelete
      summary: Deletes a task list by its id
      responses:
        "204":
          description: Task list deleted
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    put:
      tags:
        - lists
        - crud
      operationId: listsIdPut
      summary: Replaces an existing task list
      requestBody:
        description: The task list info to replace
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskList"
            example:
              title: "Clean the house"
      responses:
        "204":
          description: Task list replaced
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

  /lists/{id}/tasks:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      tags:
        - lists
        - tasks
        - crud
      operationId: listsIdTasksGet
      summary: Gets a paginated list of tasks related to an existing task list
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResult'
              example:
                total: 10
                data:
                  - id: 0
                    title: Clean bedroom
                  - id: 1
                    title: Clean kitchen
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    post:
      tags:
        - lists
        - tasks
        - crud
      operationId: listsIdTasksPost
      summary: Creates a new task on an existing task list
      requestBody:
        description: The task info to store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
            example:
              title: Clean kitchen
      responses:
        "201":
          description: The id of the new Task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Entity"
              example:
                id: 2
          links:
            tasksIdDelete:
              operationId: tasksIdDelete
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'DELETE /tasks/{id}'
            tasksIdGet:
              operationId: tasksIdGet
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'GET /tasks/{id}'
            tasksIdPut:
              operationId: tasksIdPut
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'PUT /tasks/{id}'
            tasksIdNotesGet:
              operationId: tasksIdNotesGet
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'GET /tasks/{id}/notes'
            tasksIdNotesPost:
              operationId: tasksIdNotesPost
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'POST /tasks/{id}/notes'
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

  /lists:
    get:
      tags:
        - lists
        - crud
      operationId: listsGet
      summary: Gets a paginated list of task lists
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        "200":
          description: A list of task lists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResult'
              example:
                total: 10
                data:
                  - id: 0
                    title: Clean house
                  - id: 1
                    title: Write essay
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    post:
      tags:
        - lists
        - crud
      operationId: listsPost
      summary: Creates a new task list
      requestBody:
        description: The task list info to store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskList"
            example:
              title: Write essay
      responses:
        "201":
          description: The id of the new task list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Entity"
              example:
                id: 1
          links:
            listsIdDelete:
              operationId: listsIdDelete
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'DELETE /lists/{id}'
            listsIdGet:
              operationId: listsIdGet
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'GET /lists/{id}'
            listsIdPut:
              operationId: listsIdPut
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'PUT /lists/{id}'
            listsIdTasksGet:
              operationId: listsIdTasksGet
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'GET /lists/{id}/tasks'
            listsIdTasksPost:
              operationId: listsIdTasksPost
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'POST /lists/{id}/tasks'
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

  /tasks/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    delete:
      tags:
        - tasks
        - crud
      operationId: tasksIdDelete
      summary: Deletes a task by its id
      responses:
        "204":
          description: Task deleted
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    put:
      tags:
        - tasks
        - crud
      operationId: tasksIdPut
      summary: Replaces an existing task
      requestBody:
        description: The task info to replace
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
            example:
              title: Clean main bedroom
      responses:
        "204":
          description: Task replaced
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    get:
      tags:
        - tasks
        - crud
      operationId: tasksIdGet
      summary: Gets a task by its id
      responses:
        '200':
          description: A task
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/Task"
              example:
                title: Clean bedroom
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

  /tasks/{id}/notes:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      tags:
        - tasks
        - notes
        - crud
      operationId: tasksIdNotesGet
      summary: Gets a paginated list of notes related to an existing task
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        "200":
          description: A list of notes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteResult'
              example:
                total: 1
                data:
                  - id: 0
                    content: Should wash sheets
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    post:
      tags:
        - tasks
        - notes
        - crud
      operationId: tasksIdNotesPost
      summary: Creates a new note on an existing task
      requestBody:
        description: The note info to store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
            example:
              content: "Be careful with the floor"
            
      responses:
        "201":
          description: The id of the new note
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Entity"
              example:
                id: 1
          links:
            notesIdDelete:
              operationId: notesIdDelete
              parameters:
                id: $response.body#/id
              description: |
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'DELETE /notes/{id}'
            notesIdGet:
              operationId: notesIdGet
              parameters:
                id: $response.body#/id
              description: 
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'GET /notes/{id}'
            notesIdPut:
              operationId: notesIdPut
              parameters:
                id: $response.body#/id
              description: 
                The 'id' value returned in the response can be used 
                as de 'id' parameter in 'PUT /notes/{id}'
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

  /notes/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    delete:
      tags:
        - notes
        - crud
      operationId: notesIdDelete
      summary: Deletes a note by its id
      responses:
        "204":
          description: Note deleted
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    put:
      tags:
        - notes
        - crud
      operationId: notesIdPut
      summary: Replaces an existing note
      requestBody:
        description: The note info to replace
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
            example:
              content: Should also wash sheets
      responses:
        "204":
          description: Note replaced
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'

    get:
      tags:
        - notes
        - crud
      operationId: notesIdGet
      summary: Gets a note by its id
      responses:
        '200':
          description: A note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
              example:
                content: Should wash sheets
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/UnknownError'